name: 'Notify Teams (Adaptive Card)'
description: 'Send a Teams Adaptive Card message'

inputs:
  title:
    description: 'Card title'
    required: true
  description:
    description: 'Main message content'
    required: true
  pr_url:
    description: 'URL for the action button (PR link)'
    required: true
  webhook:
    description: 'Teams Incoming Webhook URL'
    required: true
  avatar_url:
    description: 'Avatar URL for the card image (default is GitHub logo)'
    required: false
    default: 'https://images.seeklogo.com/logo-png/27/2/github-logo-png_seeklogo-273183.png'

runs:
  using: 'composite'
  steps:
    - name: Send Adaptive Card to Teams
      shell: bash
      run: |
        cat <<EOF > card.json
        {
        "type": "message",
        "attachments": [
          {
            "contentType": "application/vnd.microsoft.card.adaptive",
            "contentUrl": null,
            "content": {
              "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
              "type": "AdaptiveCard",
              "version": "1.5",
              "body": [
                {
                  "type": "ColumnSet",
                  "columns": [
                    {
                      "type": "Column",
                      "width": "auto",
                      "items": [
                        {
                          "type": "Image",
                          "url": "$AVATAR_URL",
                          "size": "Small",
                          "style": "Person"
                        }
                      ]
                    },
                    {
                      "type": "Column",
                      "width": "stretch",
                      "items": [
                        {
                          "type": "TextBlock",
                          "text": "$TITLE",
                          "wrap": true,
                          "weight": "Bolder",
                          "size": "Medium"
                        },
                        {
                          "type": "TextBlock",
                          "text": "$DESCRIPTION",
                          "wrap": true
                        }
                      ]
                    }
                  ]
            }
          }
        ]
        "actions": [
          {
            "type": "Action.OpenUrl",
            "title": "View Pull Request",
            "url": "$PR_URL"
          }
        ]
        }
        EOF

        curl -H "Content-Type: application/json" \
             -X POST \
             -d @card.json \
             "$WEBHOOK"
      env:
        TITLE: ${{ inputs.title }}
        DESCRIPTION: ${{ inputs.description }}
        PR_URL: ${{ inputs.pr_url }}
        WEBHOOK: ${{ inputs.webhook }}
        AVATAR_URL: ${{ inputs.avatar_url }}

