name: 'Notify Teams (Adaptive Card)'
description: 'Send a Teams Adaptive Card message'

inputs:
  title:
    description: 'Card title'
    required: true
  description:
    description: 'Main message content'
    required: true
  url:
    description: 'URL for the action button (e.g., PR link)'
    required: true
  webhook:
    description: 'Teams Incoming Webhook URL'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Send Adaptive Card to Teams
      shell: bash
      run: |
        cat <<EOF > card.json
        {
        "type": "message",
        "attachments": [
          {
            "contentType": "application/vnd.microsoft.card.adaptive",
            "contentUrl": null,
            "content": {
              "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
              "type": "AdaptiveCard",
              "version": "1.5",
              "body": [
                {
                  "type": "TextBlock",
                  "size": "Large",
                  "weight": "Bolder",
                  "text": "$TITLE",
                  "wrap": true
                },
                {
                  "type": "TextBlock",
                  "text": "$DESCRIPTION",
                  "wrap": true
                }
              ],
              "actions": [
                {
                  "type": "Action.OpenUrl",
                  "title": "View Pull Request",
                  "url": "$URL"
                }
              ]
            }
          }
        ]
        }
        EOF

        curl -H "Content-Type: application/json" \
             -X POST \
             -d @card.json \
             "$WEBHOOK"
      env:
        TITLE: ${{ inputs.title }}
        DESCRIPTION: ${{ inputs.description }}
        URL: ${{ inputs.url }}
        WEBHOOK: ${{ inputs.webhook }}
