name: 'Push to mirror Repository'
description: 'Push to the Epitech mirror repository'

env:
  MIRROR_URL: "git@github.com:EpitechPromo2027/G-EIP-600-NAN-6-1-eip-tugdual.de-reviers.git"

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - uses: pixta-dev/repository-mirroring-action@v1
      with:
        target_repo_url:
          ${{ env.MIRROR_URL}}
        ssh_private_key:
          ${{ secrets.GIT_SSH_PRIVATE_KEY }}
