name: "Setup Node.js and Cache Dependencies"
description: "Sets up Node.js and caches dependencies for web and server"
runs:
  using: "composite"
  steps:
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}

    - name: Setup and cache web dependencies
      uses: ../setup-node-with-cache
      with:
        working-directory: ./web

    - name: Setup and cache server dependencies
      uses: ../setup-node-with-cache
      with:
        working-directory: ./server
inputs:
  node-version:
    description: "Node.js version to set up"
    required: true
