import {
  FaArrowDown,
  FaArrowLeft,
  FaArrowRight,
  FaArrowUp,
  FaBell,
  FaCalendarAlt,
  FaChartLine,
  FaCheck,
  FaClock,
  FaCog,
  FaComments,
  FaDownload,
  FaEdit,
  FaEye,
  FaEyeSlash,
  FaHeart,
  FaHome,
  FaLock,
  FaMinus,
  FaPalette,
  FaPlus,
  FaQuestionCircle,
  FaSave,
  FaSearch,
  FaShare,
  FaStickyNote,
  FaTag,
  FaTimes,
  FaTrash,
  FaUnlock,
  FaUpload,
  FaUser,
} from 'react-icons/fa';
import {
  MdCheckCircle,
  MdClose,
  MdDashboard,
  MdError,
  MdInfo,
  MdMenu,
  MdMoreVert,
  MdNotifications,
  MdRefresh,
  MdSettings,
  MdWarning,
} from 'react-icons/md';
import {
  PiMicrophoneFill,
  PiMicrophoneSlashFill,
  PiPhoneFill,
  PiPhoneSlashFill,
  PiSpeakerSimpleHighFill,
  PiSpeakerSlashFill,
  PiVideoCameraFill,
  PiVideoCameraSlashFill,
} from 'react-icons/pi';

export const iconMap = {
  // FontAwesome icons
  home: FaHome,
  user: FaUser,
  cog: FaCog,
  search: FaSearch,
  bell: FaBell,
  heart: FaHeart,
  share: FaShare,
  edit: FaEdit,
  trash: FaTrash,
  plus: FaPlus,
  minus: FaMinus,
  check: FaCheck,
  times: FaTimes,
  'arrow-left': FaArrowLeft,
  'arrow-right': FaArrowRight,
  'arrow-up': FaArrowUp,
  'arrow-down': FaArrowDown,
  eye: FaEye,
  'eye-slash': FaEyeSlash,
  lock: FaLock,
  unlock: FaUnlock,
  download: FaDownload,
  upload: FaUpload,
  chat: FaComments,
  notes: FaStickyNote,
  help: FaQuestionCircle,
  progression: FaChartLine,
  schedule: FaCalendarAlt,
  tag: FaTag,
  clock: FaClock,
  palette: FaPalette,
  save: FaSave,

  // SimulationArea icons
  speaker: PiSpeakerSimpleHighFill,
  'speaker-off': PiSpeakerSlashFill,
  call: PiPhoneFill,
  'hang-up': PiPhoneSlashFill,
  'mic-on': PiMicrophoneFill,
  'mic-off': PiMicrophoneSlashFill,
  video: PiVideoCameraFill,
  'video-off': PiVideoCameraSlashFill,

  // Material Design icons
  dashboard: MdDashboard,
  settings: MdSettings,
  notifications: MdNotifications,
  menu: MdMenu,
  close: MdClose,
  'more-vert': MdMoreVert,
  refresh: MdRefresh,
  info: MdInfo,
  warning: MdWarning,
  error: MdError,
  'check-circle': MdCheckCircle,
} as const;

export type IconName = keyof typeof iconMap;
