import {
  FaArrowDown,
  FaArrowLeft,
  FaArrowRight,
  FaArrowUp,
  FaBell,
  FaCalendarAlt,
  FaChartLine,
  FaCheck,
  FaCog,
  FaComments,
  FaDownload,
  FaEdit,
  FaEye,
  FaEyeSlash,
  FaHeart,
  FaHome,
  FaLock,
  FaQuestionCircle,
  FaSearch,
  FaStickyNote,
  FaTimes,
  FaTrash,
  FaUnlock,
  FaUpload,
  FaUser,
} from 'react-icons/fa';
import {
  MdCheckCircle,
  MdClose,
  MdDashboard,
  MdError,
  MdInfo,
  MdMenu,
  MdMoreVert,
  MdNotifications,
  MdRefresh,
  MdSettings,
  MdWarning,
} from 'react-icons/md';
import {
  PiArrowClockwise,
  PiArrowCounterClockwise,
  PiBookmarkSimple,
  PiHighlighter,
  PiListBullets,
  PiListChecks,
  PiListNumbers,
  PiMagnifyingGlassMinus,
  PiMagnifyingGlassPlus,
  PiMicrophoneFill,
  PiMicrophoneSlashFill,
  PiMinus,
  PiPaintBrushBroad,
  PiPalette,
  PiPencilSimple,
  PiPhoneFill,
  PiPhoneSlashFill,
  PiPlus,
  PiShare,
  PiSpeakerSimpleHighFill,
  PiSpeakerSlashFill,
  PiTextAa,
  PiTextAlignCenter,
  PiTextAlignJustify,
  PiTextAlignLeft,
  PiTextAlignRight,
  PiTextB,
  PiTextIndent,
  PiTextItalic,
  PiTextOutdent,
  PiTextStrikethrough,
  PiTextTSlash,
  PiTextUnderline,
  PiTrash,
  PiVideoCameraFill,
  PiVideoCameraSlashFill,
} from 'react-icons/pi';

export const iconMap = {
  // FontAwesome icons
  home: FaHome,
  user: FaUser,
  cog: FaCog,
  search: FaSearch,
  bell: FaBell,
  heart: FaHeart,
  edit: FaEdit,
  trash: FaTrash,
  check: FaCheck,
  times: FaTimes,
  'arrow-left': FaArrowLeft,
  'arrow-right': FaArrowRight,
  'arrow-up': FaArrowUp,
  'arrow-down': FaArrowDown,
  eye: FaEye,
  'eye-slash': FaEyeSlash,
  lock: FaLock,
  unlock: FaUnlock,
  download: FaDownload,
  upload: FaUpload,
  chat: FaComments,
  notes: FaStickyNote,
  help: FaQuestionCircle,
  progression: FaChartLine,
  schedule: FaCalendarAlt,

  // Phosphor icons (used across app)
  plus: PiPlus,
  minus: PiMinus,

  // Editor icons (Phosphor)
  bold: PiTextB,
  italic: PiTextItalic,
  underline: PiTextUnderline,
  strikethrough: PiTextStrikethrough,
  'list-ul': PiListBullets,
  'list-ol': PiListNumbers,
  tasks: PiListChecks,
  'align-left': PiTextAlignLeft,
  'align-center': PiTextAlignCenter,
  'align-right': PiTextAlignRight,
  'align-justify': PiTextAlignJustify,
  indent: PiTextIndent,
  outdent: PiTextOutdent,
  undo: PiArrowCounterClockwise,
  redo: PiArrowClockwise,
  'remove-format': PiTextTSlash,
  'paint-brush': PiPaintBrushBroad,
  'search-plus': PiMagnifyingGlassPlus,
  'search-minus': PiMagnifyingGlassMinus,
  'format-color-text': PiTextAa,
  palette: PiPalette,
  highlighter: PiHighlighter,

  // SimulationArea icons (Phosphor)
  speaker: PiSpeakerSimpleHighFill,
  'speaker-off': PiSpeakerSlashFill,
  call: PiPhoneFill,
  'hang-up': PiPhoneSlashFill,
  'mic-on': PiMicrophoneFill,
  'mic-off': PiMicrophoneSlashFill,
  video: PiVideoCameraFill,
  'video-off': PiVideoCameraSlashFill,

  // Notes icons (Phosphor)
  share: PiShare,
  favorite: PiBookmarkSimple,
  delete: PiTrash,
  pencil: PiPencilSimple,

  // Material Design icons
  dashboard: MdDashboard,
  settings: MdSettings,
  notifications: MdNotifications,
  menu: MdMenu,
  close: MdClose,
  'more-vert': MdMoreVert,
  refresh: MdRefresh,
  info: MdInfo,
  warning: MdWarning,
  error: MdError,
  'check-circle': MdCheckCircle,
} as const;

export type IconName = keyof typeof iconMap;
