name: "Feature Request"
description: "Propose a new feature"
title: "[Feature] <title>"
labels: [feature]
body:
  - type: input
    id: feature-summary
    attributes:
      label: "What do you want?"
      description: "Short summary."
      placeholder: "e.g. Add dark mode support"
    validations:
      required: true
  - type: textarea
    id: feature-description
    attributes:
      label: "Details"
      description: "Describe the feature and why we need it."
      placeholder: "What problem does this solve? How should it work?"
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: "Extra info (optional)"
      description: "Links, context, or notes."
      placeholder: "Context, screenshots, or related issues."
    validations:
      required: false
