name: 'Playwright Tests'
description: 'Run Playwright e2e tests'
runs:
  using: 'composite'
  steps:
    - name: Cache Playwright Browsers
      uses: actions/cache@v4
      id: playwright-cache
      with:
        path: |
          ~/.cache/ms-playwright
          ~/Library/Caches/ms-playwright
          %USERPROFILE%\AppData\Local\ms-playwright
        key: ${{ runner.os }}-playwright-${{ hashFiles('package-lock.json') }}-${{ hashFiles('web/playwright.config.ts') }}-${{ hashFiles('web/package.json') }}
        restore-keys: |
          ${{ runner.os }}-playwright-${{ hashFiles('package-lock.json') }}-
          ${{ runner.os }}-playwright-

    - name: Install Playwright Browsers and System Dependencies
      shell: bash
      run: npm run playwright:install --workspace=web
      if: steps.playwright-cache.outputs.cache-hit != 'true'

    - name: Install System Dependencies Only (cache hit)
      shell: bash
      run: npm run playwright:install-deps --workspace=web
      if: steps.playwright-cache.outputs.cache-hit == 'true'

    - name: Run Playwright e2e tests web
      shell: bash
      run: npm run e2e:web

    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: ./web/playwright-report/
        retention-days: 14
