name: 'Setup Node.js with Cache for npm Dependencies'
description: 'Sets up Node.js (v23.x) and caches/installs npm dependencies in a subdirectory'

inputs:
  working-directory:
    description: 'The subdirectory containing the package.json and node_modules'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Set up Node.js (v23.x)
      uses: actions/setup-node@v4
      with:
        node-version: '23.x'

    - name: Cache npm Modules
      uses: actions/cache@v4
      with:
        path: ${{ inputs.working-directory }}/node_modules
        key: ${{ runner.os }}-node-${{ hashFiles(format('{0}/package-lock.json', inputs.working-directory)) }}
        restore-keys: |
          ${{ runner.os }}-node-
          ${{ runner.os }}-

    - name: Install Dependencies
      shell: bash
      run: npm ci
      working-directory: ${{ inputs.working-directory }}
