name: "Setup Node.js with Cache for npm Dependencies"
description: "Sets up Node.js (v23.x) and caches/installs npm dependencies for workspace or subdirectory"

inputs:
  working-directory:
    description: "The subdirectory containing the package.json and node_modules (optional, defaults to root for workspace)"
    required: false
    default: "."

runs:
  using: "composite"
  steps:
    - name: Set up Node.js (v23.x)
      uses: actions/setup-node@v4
      with:
        node-version: "23.x"

    - name: Cache npm Modules
      uses: actions/cache@v4
      id: npm-cache
      with:
        path: |
          ${{ inputs.working-directory }}/node_modules
          ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles(format('{0}/package-lock.json', inputs.working-directory)) }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install Dependencies
      if: steps.npm-cache.outputs.cache-hit != 'true'
      shell: bash
      run: npm ci
      working-directory: ${{ inputs.working-directory }}
