/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.
// Import Routes
import { Route as rootRoute } from './routes/__root';
import { Route as AboutImport } from './routes/about';
import { Route as AiChatImport } from './routes/ai-chat';
import { Route as CvAnalysisImport } from './routes/cv-analysis';
import { Route as DashboardImport } from './routes/dashboard';
import { Route as DiaryImport } from './routes/diary';
import { Route as IndexImport } from './routes/index';
import { Route as LoginImport } from './routes/login';
import { Route as NotesImport } from './routes/notes';
import { Route as ProfileImport } from './routes/profile';
import { Route as ProgressionImport } from './routes/progression';
import { Route as SignupImport } from './routes/signup';
import { Route as SimulationsImport } from './routes/simulations';

// Create/Update Routes

const SimulationsRoute = SimulationsImport.update({
  id: '/simulations',
  path: '/simulations',
  getParentRoute: () => rootRoute,
} as any);

const SignupRoute = SignupImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRoute,
} as any);

const ProgressionRoute = ProgressionImport.update({
  id: '/progression',
  path: '/progression',
  getParentRoute: () => rootRoute,
} as any);

const ProfileRoute = ProfileImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRoute,
} as any);

const NotesRoute = NotesImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRoute,
} as any);

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any);

const DiaryRoute = DiaryImport.update({
  id: '/diary',
  path: '/diary',
  getParentRoute: () => rootRoute,
} as any);

const DashboardRoute = DashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any);

const CvAnalysisRoute = CvAnalysisImport.update({
  id: '/cv-analysis',
  path: '/cv-analysis',
  getParentRoute: () => rootRoute,
} as any);

const AiChatRoute = AiChatImport.update({
  id: '/ai-chat',
  path: '/ai-chat',
  getParentRoute: () => rootRoute,
} as any);

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any);

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexImport;
      parentRoute: typeof rootRoute;
    };
    '/about': {
      id: '/about';
      path: '/about';
      fullPath: '/about';
      preLoaderRoute: typeof AboutImport;
      parentRoute: typeof rootRoute;
    };
    '/ai-chat': {
      id: '/ai-chat';
      path: '/ai-chat';
      fullPath: '/ai-chat';
      preLoaderRoute: typeof AiChatImport;
      parentRoute: typeof rootRoute;
    };
    '/cv-analysis': {
      id: '/cv-analysis';
      path: '/cv-analysis';
      fullPath: '/cv-analysis';
      preLoaderRoute: typeof CvAnalysisImport;
      parentRoute: typeof rootRoute;
    };
    '/dashboard': {
      id: '/dashboard';
      path: '/dashboard';
      fullPath: '/dashboard';
      preLoaderRoute: typeof DashboardImport;
      parentRoute: typeof rootRoute;
    };
    '/diary': {
      id: '/diary';
      path: '/diary';
      fullPath: '/diary';
      preLoaderRoute: typeof DiaryImport;
      parentRoute: typeof rootRoute;
    };
    '/login': {
      id: '/login';
      path: '/login';
      fullPath: '/login';
      preLoaderRoute: typeof LoginImport;
      parentRoute: typeof rootRoute;
    };
    '/notes': {
      id: '/notes';
      path: '/notes';
      fullPath: '/notes';
      preLoaderRoute: typeof NotesImport;
      parentRoute: typeof rootRoute;
    };
    '/profile': {
      id: '/profile';
      path: '/profile';
      fullPath: '/profile';
      preLoaderRoute: typeof ProfileImport;
      parentRoute: typeof rootRoute;
    };
    '/progression': {
      id: '/progression';
      path: '/progression';
      fullPath: '/progression';
      preLoaderRoute: typeof ProgressionImport;
      parentRoute: typeof rootRoute;
    };
    '/signup': {
      id: '/signup';
      path: '/signup';
      fullPath: '/signup';
      preLoaderRoute: typeof SignupImport;
      parentRoute: typeof rootRoute;
    };
    '/simulations': {
      id: '/simulations';
      path: '/simulations';
      fullPath: '/simulations';
      preLoaderRoute: typeof SimulationsImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/about': typeof AboutRoute;
  '/ai-chat': typeof AiChatRoute;
  '/cv-analysis': typeof CvAnalysisRoute;
  '/dashboard': typeof DashboardRoute;
  '/diary': typeof DiaryRoute;
  '/login': typeof LoginRoute;
  '/notes': typeof NotesRoute;
  '/profile': typeof ProfileRoute;
  '/progression': typeof ProgressionRoute;
  '/signup': typeof SignupRoute;
  '/simulations': typeof SimulationsRoute;
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/about': typeof AboutRoute;
  '/ai-chat': typeof AiChatRoute;
  '/cv-analysis': typeof CvAnalysisRoute;
  '/dashboard': typeof DashboardRoute;
  '/diary': typeof DiaryRoute;
  '/login': typeof LoginRoute;
  '/notes': typeof NotesRoute;
  '/profile': typeof ProfileRoute;
  '/progression': typeof ProgressionRoute;
  '/signup': typeof SignupRoute;
  '/simulations': typeof SimulationsRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  '/': typeof IndexRoute;
  '/about': typeof AboutRoute;
  '/ai-chat': typeof AiChatRoute;
  '/cv-analysis': typeof CvAnalysisRoute;
  '/dashboard': typeof DashboardRoute;
  '/diary': typeof DiaryRoute;
  '/login': typeof LoginRoute;
  '/notes': typeof NotesRoute;
  '/profile': typeof ProfileRoute;
  '/progression': typeof ProgressionRoute;
  '/signup': typeof SignupRoute;
  '/simulations': typeof SimulationsRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/'
    | '/about'
    | '/ai-chat'
    | '/cv-analysis'
    | '/dashboard'
    | '/diary'
    | '/login'
    | '/notes'
    | '/profile'
    | '/progression'
    | '/signup'
    | '/simulations';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/'
    | '/about'
    | '/ai-chat'
    | '/cv-analysis'
    | '/dashboard'
    | '/diary'
    | '/login'
    | '/notes'
    | '/profile'
    | '/progression'
    | '/signup'
    | '/simulations';
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/ai-chat'
    | '/cv-analysis'
    | '/dashboard'
    | '/diary'
    | '/login'
    | '/notes'
    | '/profile'
    | '/progression'
    | '/signup'
    | '/simulations';
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AboutRoute: typeof AboutRoute;
  AiChatRoute: typeof AiChatRoute;
  CvAnalysisRoute: typeof CvAnalysisRoute;
  DashboardRoute: typeof DashboardRoute;
  DiaryRoute: typeof DiaryRoute;
  LoginRoute: typeof LoginRoute;
  NotesRoute: typeof NotesRoute;
  ProfileRoute: typeof ProfileRoute;
  ProgressionRoute: typeof ProgressionRoute;
  SignupRoute: typeof SignupRoute;
  SimulationsRoute: typeof SimulationsRoute;
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AiChatRoute: AiChatRoute,
  CvAnalysisRoute: CvAnalysisRoute,
  DashboardRoute: DashboardRoute,
  DiaryRoute: DiaryRoute,
  LoginRoute: LoginRoute,
  NotesRoute: NotesRoute,
  ProfileRoute: ProfileRoute,
  ProgressionRoute: ProgressionRoute,
  SignupRoute: SignupRoute,
  SimulationsRoute: SimulationsRoute,
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/ai-chat",
        "/cv-analysis",
        "/dashboard",
        "/diary",
        "/login",
        "/notes",
        "/profile",
        "/progression",
        "/signup",
        "/simulations"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/ai-chat": {
      "filePath": "ai-chat.tsx"
    },
    "/cv-analysis": {
      "filePath": "cv-analysis.tsx"
    },
    "/dashboard": {
      "filePath": "dashboard.tsx"
    },
    "/diary": {
      "filePath": "diary.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/notes": {
      "filePath": "notes.tsx"
    },
    "/profile": {
      "filePath": "profile.tsx"
    },
    "/progression": {
      "filePath": "progression.tsx"
    },
    "/signup": {
      "filePath": "signup.tsx"
    },
    "/simulations": {
      "filePath": "simulations.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
